---
# validate-vars default vars

# bm = baremetal
# rwn = remote worker node
# sno = single node openshift
rh_lab_cluster_types:
- bm
- rwn
- sno

ibmcloud_cluster_types:
- bm
- sno

bm_network_types:
- OVNKubernetes
- OpenShiftSDN

ocp_build_types:
- ga
- dev
