---
# generate-discovery-iso default vars

# This will be your bastion machine (if you run setup-bastion playbook)
assisted_installer_host: "{{ groups['bastion'][0] }}"
assisted_installer_port: 8090

# This will be your bastion machine (if you run setup-bastion playbook)
disconnected_registry_host: "{{ groups['bastion'][0] }}"
disconnected_registry_port: 5000

# This will be your bastion machine (if you run setup-bastion playbook)
http_store_host: "{{ groups['bastion'][0] }}"
http_store_port: 8081
