---
# cluster_name applies only to mno clusters, sno clusters use base host name as the cluster name
cluster_name: mno
base_dns_name: example.com

# Setup and use coredns instead of dnsmasq
setup_coredns: true

# Appends each entry to /etc/hosts of bastion machine during cluster install to
# allow sshuttle easy resolution when proxying into cluster
etc_hosts_ingress_routes:
- aap-ansible-automation-platform
- aap-controller-ansible-automation-platform
- aap-eda-ansible-automation-platform
- aap-hub-ansible-automation-platform
- acm-cli-downloads
- agent-registration-multicluster-engine
- alertmanager-main-openshift-monitoring
- alertmanager-open-cluster-management-observability
- assisted-image-service-multicluster-engine
- assisted-service-multicluster-engine
- canary-openshift-ingress-canary
- cluster-proxy-anp
- cluster-proxy-user
- console-openshift-console
- dittybopper-dittybopper
- downloads-openshift-console
- federate-openshift-user-workload-monitoring
- grafana-open-cluster-management-observability
- hcp-cli-download-multicluster-engine
- images-multicluster-engine
- kam-openshift-gitops
- minio-minio
- multicloud-console
- multicluster-global-hub-grafana-multicluster-global-hub
- oauth-openshift
- observatorium-api-open-cluster-management-observability
- openshift-gitops-server-openshift-gitops
- prometheus-k8s-federate-openshift-monitoring
- prometheus-k8s-openshift-monitoring
- rbac-query-proxy-open-cluster-management-observability
- search-api-open-cluster-management
- thanos-querier-openshift-monitoring
- thanos-ruler-openshift-user-workload-monitoring

# Default number of additional dns entries to add in the event we have hypervisor machines with VMs.
# Ignore if you are not doing anything with hypervisor machines and VMs
compact_cluster_dns_count: 4000
standard_cluster_dns_count: 4000
