---
# create-inventory default vars

ocp_inventory_override: ''

# Master nodes "consume" the first 7 address out of the controlplane_network, workers start after this offset
mno_worker_node_offset: 7

################################################################################
# Var(s) for hypervisors and hypervisor hosted VMs
################################################################################
# Enables placing extra machines as hypervisors in the inventory and generating the inventory of VMs
hv_inventory: false

# ssh password for hypervisors
hv_ssh_pass:

hv_ip_offset: 0

hv_vm_prefix: vm
hv_vm_ip_offset: 1000

# "Emulated bare-metal" VM Size
hv_vm_cpu_count: 8
hv_vm_memory_size: 18
hv_vm_disk_size: 120

# Bandwith limits for VMs (in KB/s)
hv_vm_bandwidth_limit: false
hv_vm_bandwidth_average: 11500
hv_vm_bandwidth_peak: 12500
hv_vm_bandwidth_burst: 11750

# Path for VMs on disk2
disk2_mount_path: /mnt/disk2

# If HV is setup, how many workers are VMs
# This adds vm workers to the workers section of the inventory
hybrid_worker_count: 0
