---
# Set hostname and role

- name: Set the host bmc address
  set_fact:
    host_bmc: "{{ (discovered_host.inventory | from_json).bmc_address }}"
  when: lab in cloud_labs

- name: Set the host id and list of mac addresses
  set_fact:
    host_id: "{{ discovered_host.id }}"
    host_macs: "{{ (discovered_host.inventory | from_json) | json_query('interfaces[].mac_address') }}"

- name: Set the hostname and role via mac address
  set_fact:
    hostname: "{{ item }}"
    host_role: "{{ hostvars[item]['role'] }}"
  when:
    - lab in rh_labs
    - hostvars[item]['mac_address'] in host_macs
  loop: "{{ inventory_nodes }}"
  loop_control:
    label: "{{ hostvars[item]['bmc_address'] }}"

- name: Set the hostname and role via bmc address
  set_fact:
    hostname: "{{ item }}"
    host_role: "{{ hostvars[item]['role'] }}"
  when:
    - lab in cloud_labs
    - hostvars[item]['bmc_address'] == host_bmc
  loop: "{{ inventory_nodes }}"
  loop_control:
    label: "{{ hostvars[item]['bmc_address'] }}"

- name: Set hostname and role for {{ hostname }}
  uri:
    url: "http://{{ assisted_installer_host }}:{{ assisted_installer_port }}/api/assisted-install/v2/infra-envs/{{ ai_infraenv_id }}/hosts/{{ host_id }}"
    method: PATCH
    body_format: json
    status_code: [201]
    return_content: true
    body: {
        "host_name": "{{ hostname }}",
        "host_role": "{{ host_role }}"
    }
