---
# bastion-disconnected-registry default vars

# This will be your bastion machine (if you run setup-bastion playbook)
disconnected_registry_host: "{{ groups['bastion'][0] }}"
disconnected_registry_port: 5000

registry_path: /opt/registry

registry_user: registry
registry_password: registry

registry_container_image: quay.io/nchhabra/ocp4:latest

registry_repo: ocp4/openshift4

# Ideally the name/tags match the original source operator-index
operator_index_container_image: registry.redhat.io/redhat/redhat-operator-index:v4.11
operator_index_name: redhat-operator-index
operator_index_tag: v4.11

operators_to_sync: cluster-logging,local-storage-operator,openshift-gitops-operator,performance-addon-operator,ptp-operator,sriov-network-operator
