---
# Create and deploy a cluster with the Assisted Installer and join remote worker
# nodes using a LiveCD and ignition configuration
#
# Example Usage:
#
# ansible-playbook -i ansible/inventory/cloud42.local ansible/deploy.yml
#

- name: Create 3 node cluster with assisted installer and join remote worker nodes
  hosts: bastion
  vars_files:
  - vars/all.yml
  roles:
  - create-ai-cluster
  - generate-discovery-iso
  - role: boot-iso
    vars:
      inventory_group: controlplane
      boot_iso_url: "http://{{ http_store_host }}:{{ http_store_port }}/{{ discovery_iso_file_name }}"
      iso_name: "{{ discovery_iso_file_name }}"
  - wait-hosts-discovered
  - install-cluster
  - post-cluster-install
  - generate-livecd
  - role: boot-iso
    vars:
      inventory_group: rwn
      boot_iso_url: "http://{{ http_store_host }}:{{ http_store_port }}/{{ cluster_name }}-worker.iso"
      iso_name: "{{ cluster_name }}-worker.iso"
  - wait-for-rwn-to-join
