---
# Create and deploy a cluster with the Assisted Installer
#
# Example Usage:
#
# ansible-playbook -i ansible/inventory/cloud42.local ansible/mno-deploy.yml
#

- name: Creates a multi node cluster with the assisted-installer
  hosts: bastion
  vars_files:
  - vars/lab.yml
  - vars/all.yml
  roles:
  - validate-vars
  - ocp-release
  - create-ai-cluster
  - generate-discovery-iso
  - role: boot-iso
    vars:
      inventory_group: controlplane
      index: 3
  - role: boot-iso
    vars:
      inventory_group: worker
      index: "{{ worker_node_count }}"
  - wait-hosts-discovered
  - configure-local-storage
  - install-cluster
  - mno-post-cluster-install
