---
# bastion-install default vars

coredns_url: https://github.com/coredns/coredns/releases/download/v1.10.1/coredns_1.10.1_linux_amd64.tgz
grpcurl_url: https://github.com/fullstorydev/grpcurl/releases/download/v1.8.1/grpcurl_1.8.1_linux_x86_64.tar.gz
kubeburner_url: https://github.com/cloud-bulldozer/kube-burner/releases/download/v1.7.6/kube-burner-V1.7.6-linux-arm64.tar.gz
minio_client_url: https://dl.min.io/client/mc/release/linux-amd64/mc
yq_url: https://github.com/mikefarah/yq/releases/download/v4.40.3/yq_linux_amd64.tar.gz

# Crucible specific vars
install_rh_crucible: false
rh_crucible_url: https://github.com/perftool-incubator/crucible


# Since the use of tc on the bastion machine is rare and only for remote worker node testing in Red Hat labs, we
# disable rebooting the bastion machine by default.
bastion_install_tc_reboot: false

# promdump
promdump_url: https://github.com/ihcsim/promdump/releases/download/v0.2.5/kubectl-promdump-linux-amd64-v0.2.5.tar.gz
promdump_tarball: /tmp/kubectl-promdump-linux-amd64.tar.gz
